// generated by logging out the response as JSON
// then convertedit to a single type with https://transform.tools/json-to-typescript
// updated any {} to Record<string, unknown>

export type PortableSchema = {
	jsonType: string
	type: {
		name: string
		title: string
		type: any
		jsonType: string
	}
	name: string
	title: string
	fields: {
		name: string
		type: {
			jsonType: string
			type: {
				name: string
				type: any
				jsonType: string
				of: any[]
			}
			name: string
			title: string
			of: {
				type: {
					name: string
					title: string
					type: any
					jsonType: string
				}
				name: string
				title: string
				jsonType: string
				options: Record<string, unknown>
				fields: {
					name: string
					type: {
						jsonType: string
						type: {
							name: string
							type: any
							jsonType: string
							of?: any[]
							title?: string
						}
						name: string
						title: string
						of?: {
							jsonType: string
							type: {
								name: string
								title: string
								type: any
								jsonType: string
							}
							name: string
							title: string
							fields: {
								name: string
								type: {
									jsonType: string
									type: {
										name: string
										title?: string
										type: any
										jsonType: string
										of?: any[]
									}
									name: string
									title: string
									description?: string
									preview?: Record<string, unknown>
									of?: {
										jsonType: string
										type: {
											name: string
											title: string
											type: any
											jsonType: string
										}
										name: string
										title: string
										preview: Record<string, unknown>
									}[]
								}
							}[]
							i18nTitleKey?: string
							options: {
								modal?: {
									type: string
								}
							}
							orderings?: any[]
							fieldsets?: {
								single: boolean
								field: {
									name: string
									type: {
										jsonType: string
										type: {
											name: string
											title: string
											type: any
											jsonType: string
										}
										name: string
										title: string
										description: string
										preview: Record<string, unknown>
									}
								}
							}[]
							groups?: any[]
							preview: {
								select: {
									href?: string
									text?: string
									marks?: string
								}
							}
							annotations?: {
								jsonType: string
								type: {
									name: string
									title: string
									type: any
									jsonType: string
								}
								name: string
								title: string
								fields: {
									name: string
									type: {
										jsonType: string
										type: {
											name: string
											title: string
											type: any
											jsonType: string
										}
										name: string
										title: string
										description: string
										preview: Record<string, unknown>
									}
								}[]
								i18nTitleKey: string
								options: {
									modal: {
										type: string
									}
								}
								orderings: any[]
								fieldsets: {
									single: boolean
									field: {
										name: string
										type: {
											jsonType: string
											type: {
												name: string
												title: string
												type: any
												jsonType: string
											}
											name: string
											title: string
											description: string
											preview: Record<string, unknown>
										}
									}
								}[]
								groups: any[]
								preview: {
									select: {
										href: string
									}
								}
							}[]
							decorators?: {
								title: string
								value: string
								i18nTitleKey: string
							}[]
							marks?: any[]
						}[]
						options?: {
							list: {
								title: string
								value: string
								i18nTitleKey: string
							}[]
						}
						preview?: Record<string, unknown>
					}
				}[]
				preview: {
					select: Record<string, unknown>
				}
			}[]
		}
	}[]
	options: Record<string, unknown>
	orderings: any[]
	fieldsets: {
		single: boolean
		field: {
			name: string
			type: {
				jsonType: string
				type: {
					name: string
					type: any
					jsonType: string
					of: any[]
				}
				name: string
				title: string
				of: {
					type: {
						name: string
						title: string
						type: any
						jsonType: string
					}
					name: string
					title: string
					jsonType: string
					options: Record<string, unknown>
					fields: {
						name: string
						type: {
							jsonType: string
							type: {
								name: string
								type: any
								jsonType: string
								of?: any[]
								title?: string
							}
							name: string
							title: string
							of?: {
								jsonType: string
								type: {
									name: string
									title: string
									type: any
									jsonType: string
								}
								name: string
								title: string
								fields: {
									name: string
									type: {
										jsonType: string
										type: {
											name: string
											title?: string
											type: any
											jsonType: string
											of?: any[]
										}
										name: string
										title: string
										description?: string
										preview?: Record<string, unknown>
										of?: {
											jsonType: string
											type: {
												name: string
												title: string
												type: any
												jsonType: string
											}
											name: string
											title: string
											preview: Record<string, unknown>
										}[]
									}
								}[]
								i18nTitleKey?: string
								options: {
									modal?: {
										type: string
									}
								}
								orderings?: any[]
								fieldsets?: {
									single: boolean
									field: {
										name: string
										type: {
											jsonType: string
											type: {
												name: string
												title: string
												type: any
												jsonType: string
											}
											name: string
											title: string
											description: string
											preview: Record<string, unknown>
										}
									}
								}[]
								groups?: any[]
								preview: {
									select: {
										href?: string
										text?: string
										marks?: string
									}
								}
								annotations?: {
									jsonType: string
									type: {
										name: string
										title: string
										type: any
										jsonType: string
									}
									name: string
									title: string
									fields: {
										name: string
										type: {
											jsonType: string
											type: {
												name: string
												title: string
												type: any
												jsonType: string
											}
											name: string
											title: string
											description: string
											preview: Record<string, unknown>
										}
									}[]
									i18nTitleKey: string
									options: {
										modal: {
											type: string
										}
									}
									orderings: any[]
									fieldsets: {
										single: boolean
										field: {
											name: string
											type: {
												jsonType: string
												type: {
													name: string
													title: string
													type: any
													jsonType: string
												}
												name: string
												title: string
												description: string
												preview: Record<string, unknown>
											}
										}
									}[]
									groups: any[]
									preview: {
										select: {
											href: string
										}
									}
								}[]
								decorators?: {
									title: string
									value: string
									i18nTitleKey: string
								}[]
								marks?: any[]
							}[]
							options?: {
								list: {
									title: string
									value: string
									i18nTitleKey: string
								}[]
							}
							preview?: Record<string, unknown>
						}
					}[]
					preview: {
						select: Record<string, unknown>
					}
				}[]
			}
		}
	}[]
	groups: any[]
	preview: {
		select: {
			title: string
		}
	}
}
